### ISSUE TITLE
密码错误

### ISSUE THREAD

**Issue by yintian710** [PRaichu/yiban#1]
md5 加密后的密码不对了，可能是易班的加密换了
但是我现在用的抓包工具抓不到易班的登陆了，老哥有啥办法吗

**Comment by PRaichu** [comment]
> md5加密后的密码不对了，可能是易班的加密换了
> 但是我现在用的抓包工具抓不到易班的登陆了，老哥有啥办法吗

我刚刚试了，是正常的啊

**Comment by yintian710** [comment]
> > md5加密后的密码不对了，可能是易班的加密换了
> > 但是我现在用的抓包工具抓不到易班的登陆了，老哥有啥办法吗
> 
> 我刚刚试了，是正常的啊

是可以正常登陆吗

**Comment by PRaichu** [comment]
> > > md5加密后的密码不对了，可能是易班的加密换了
> > > 但是我现在用的抓包工具抓不到易班的登陆了，老哥有啥办法吗
> > 
> > 
> > 我刚刚试了，是正常的啊
> 
> 是可以正常登陆吗

是的，我这里可以正常返回

**Comment by yintian710** [comment]
基于requests实现的自动打卡程序

**Comment by yintian710** [comment]
基于requests实现的自动打卡程序

本地化后运行提示

Traceback (most recent call last):
  File "C:\Users\银天\AppData\Roaming\Python\Python37\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-47ea309c90fc>", line 1, in <module>
    runfile('C:/py/jyf/spider/res_yiban.py', wdir='C:/py/jyf/spider')
  File "C:\Program Files\JetBrains\PyCharm 2019.1.1\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2019.1.1\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/py/jyf/spider/res_yiban.py", line 64, in <module>
    'sfzx.dm': json.loads(last_text)['sfzx'],
  File "C:\Users\银天\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\银天\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\银天\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 5 column 1 (char 8)

查看json.text后发现

		# 登录
		session_requests = requests.session()
		login_res = session_requests.post(url_login, headers=headers, data=data)
		login_res = login_res.text
		print(login_res)

返回值为 
{"msg":"帐号或密码错误!","error":true,"url":null}
